### PR TITLE
Enable Full Screen Boot Animation for Hlte Devices

### PR DESCRIPTION
**Pull request by Joshndroid**
added - TARGET_SCREEN_ASPECT_RATIO := 16-by-9 flag to enable full screen temase boot animation to be used

### CODE REVIEW

**Comment by temasek** [comment]
Can you resubmit your boot animations?

**Comment by Joshndroid** [comment]
yep taking a look now, just seen your twitter comment

**Comment by temasek** [comment]
Ya....your pull request on vendor/cm got lots of errors generated by build

**Comment by Joshndroid** [comment]
new cm vendor since original push must have broken it

**Pull request closed without merging**
